# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a445565a90e4d8fae82bcd8370f768ad98a0c374affc6c10e87b2fc0114c1212ed372300a0287e29795a9bc04f8d50ac7ded54f823941ee4da015a74c4f31aa1

test:
  secret_key_base: d63ead6218a22ffa9f22e09acb6c3e52f914a895b63e462a58f2e8a1e6443c168d2218785330b89014985cf2b5d2a2af842db05d43cbe5a6881b73983caad522

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
